### ISSUE TITLE
Draw a parametric equation 

### ISSUE THREAD

**Issue by OmarShehata** [StoDevX/humke-4d-geometry#17]
I think the hard part here is just figuring out the interface. Do we assume a single parameter, or can you have more? 

Drawing it should be similar to #10 .

**Comment by petersbob** [comment]
As far as I know, one parameter will give you a curve, two a surface, and three a surface with volume. From the talking to Humke, it seems like he is interested in two and three.

**Comment by OmarShehata** [comment]
So we should have up to 2 for 2D mode, and up to 3 for 3D and 4D modes? Or just as many parameters as dimensions?

**Comment by petersbob** [comment]
that sounds about right. We'll need him to elaborate a bit more. If you check out the requirements, he specifies three parameters for three dimensions.

**Comment by OmarShehata** [comment]
Completed by #25
