### ISSUE TITLE
Flip axis label under "viewing controls"

### ISSUE THREAD

**Issue by elijahverdoorn** [StoDevX/humke-4d-geometry#2]
The axis label under "Viewing Controls" should be flipped (so it's always normal). So in 3D, choosing X means X changes and you see sections cutting through the Y-Z plane (he called this "seeing the level sets of X")

From the notes that @OmarShehata took of the 2/16 Meeting

**Comment by OmarShehata** [comment]
Completed by this PR https://github.com/StoDevX/humke-4d-geometry/pull/9

**Comment by OmarShehata** [comment]
Completed by this PR https://github.com/StoDevX/humke-4d-geometry/pull/9
