### ISSUE TITLE
Make ThreeJS axis and coordinate system

### ISSUE THREAD

**Issue by petersbob** [StoDevX/humke-4d-geometry#41]
Create a utility function with the ability to create:
1, 2, 3, or 4 axis with label.

Grid

**Comment by OmarShehata** [comment]
Make sure you can also set the width of the lines (for axes and grid)

**Comment by petersbob** [comment]
Close to closing with the commit dfbd82e8e1dea3b5556aa2fbe0848dbd2d1fb2c9 but text is fuzzy.

I'm trying to recreate this example that uses canvas elements as sprites : https://stemkoski.github.io/Three.js/Sprite-Text-Labels.html

Having a hard time figuring the issue out.

**Comment by OmarShehata** [comment]
I've done something exactly like this before with PlayCanvas. I can take a look. @petersbob

**Comment by OmarShehata** [comment]
We can consider this closed with https://github.com/StoDevX/humke-4d-geometry/commit/7fa0c05f69ec2fe7f547caeb5d915b25826d7276. The text problem is a separate issue to be fixed.
