### ISSUE TITLE
The Position of Camera and Actual Objects in 2D (May be happen in 3D, 4D)

### ISSUE THREAD

**Issue by ten2ten2** [StoDevX/humke-4d-geometry#48]
In 2D, what we are doing now is to set z-position of objects to be 0, and move the z-position of camera. This could cause some problems. See this [commit](https://github.com/StoDevX/humke-4d-geometry/commit/5cfc9e248200e0d9b4d3714e89e8ded8470f4d6b). The u_resolution of shader depends on the size of canvas, not the size of grid (in pixels). If we set z-position of objects (shader plane, grid, etc.) to be 0, there is an issue to get the actual size of grid in pixels. The same problem may also be happen in 3D, 4D mode.

**Comment by OmarShehata** [comment]
I think this has now been fixed since we figured out how to get the real world position from the vertex shader, right? @pang-tian-yu

**Comment by ten2ten2** [comment]
I think so.
