### ISSUE TITLE
Change resolution into a dropdown

### ISSUE THREAD

**Issue by OmarShehata** [StoDevX/humke-4d-geometry#58]
Resolution is currently a slider. Instead, it should be a drop down, with "low", "medium", and "high", where "high" is the magic 112 number.

**Comment by ten2ten2** [comment]
Resolution options works only in 3D cartesian. Do we need to let it work in all 2D and 3D mode or just show this option in 3D cartesian?

**Comment by OmarShehata** [comment]
Good question @pang-tian-yu . I think we don't need it in 2D. But we should have it in 4D cartesian because that will control the resolution of the slices.

**Comment by OmarShehata** [comment]
This broke 4D cartesian rendering because it was not converting the word "high" into a number (another issue that comes from duplicated code). I fixed this, and the resolution is now working perfectly well.
