### ISSUE TITLE
Make checkboxes actually work

### ISSUE THREAD

**Issue by OmarShehata** [StoDevX/humke-4d-geometry#59]
Right now we're kind of using the checkboxes to do different and arbitrary functions in the different modes. We should re-think their names and what they do. I'm thinking:

- Show right view
  - Deselecting this would hide the right view
- Show left view
  - Deselecting this would hide the left view
- Whole shape slicing 
  - Selecting this toggle whether the rest of the shape appears in the slice with 10% opacity. 
  - Only available in 2D view.

**Comment by ten2ten2** [comment]
I just added the left/right view checkboxes.

For the whole shape slicing, I don't think it is feasible in 3D unless we change the right view to 3D. Or am I misunderstanding?

**Comment by OmarShehata** [comment]
You're right @pang-tian-yu . I was thinking this option would only appear in 2D for now. Although it would be nice in the future if we could somehow render the intersection in 3D space to show you exactly where it is. It's not needed for the class in January I think.

**Comment by OmarShehata** [comment]
I think the UI is clean and up to date now. All options now actually do something when present and are named correctly.
